site_name: 程序与设计
repo_name: 'worst001/mkdocs_program_design'  # 将 'username/repository' 更改为你的 GitHub 用户名和仓库名
repo_url: 'https://github.com/worst001/mkdocs_program_design'  # 更改为你的 GitHub 仓库 URL

theme:
  name: material
  palette:
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: purple
    accent: purple
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: purple
    accent: purple
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

nav:
  - Home: index.md
  - Markdown:
    - 基本语法与用法: Markdown/README/README.md
    - 表情emoji: Markdown/README/emoji.md
    - 官方教程: https://markdown.com.cn/basic-syntax/
    - mkdocs: https://www.mkdocs.org/getting-started/
  - Latex:
    - Latex 自用脑图: https://www.yuque.com/hanwenhao-bs03y/tncnv7/iy0aay0hgghfhqgn?singleDoc# 《Latex》
    - Latex 中文手册: https://albertyzp.github.io/2019/10/15/LaTex%E5%9F%BA%E7%A1%80%E6%89%8B%E5%86%8C/#%E4%B8%80-latex%E5%9F%BA%E6%9C%AC%E6%A6%82%E5%BF%B5
  - Matlab:
    - Matlab 官方手册: https://ww2.mathworks.cn/help/matlab/
  - Tmux: https://louiszhai.github.io/2017/09/30/tmux/
  - Vim:
    - Vim 自用笔记: Vim/Vim.md
    - Vim 手册: Vim/user_manual-2.4.0.pdf
    - 自用 Vim 配置备份: https://github.com/worst001/vim_0
    - 配套工具:
      - NeoVim: https://github.com/neovim/neovim
      - CocNvim: https://github.com/neoclide/coc.nvim
      - Packer与Telescope: https://github.com/nvim-telescope/telescope.nvim
      - FZF: https://github.com/junegunn/fzf
      - Joshuto: https://github.com/kamiyaa/joshuto
      - VimSpector: https://github.com/puremourning/vimspector
  - Emacs:
    - SpaceEmacs: https://www.spacemacs.org/
    - Lisp: https://oneforalone.github.io/cl-cookbook-cn/#/
    - MELPA 中心: https://melpa.org/#/
  - 设计模式:
    - 自用笔记: 设计模式/设计模式.md
    - 理论与详解: https://refactoringguru.cn/design-patterns/catalog
    - 各语言模板总览: https://github.com/DovAmir/awesome-design-patterns

